# This workflow will install Python dependencies, ChromeDriver and run the reservation

# Days to run: 
# Wednesday -> Reserves Monday
# Thursday  -> Reserves Tuesday
# Friday    -> Reserves Wednesday
# Saturday  -> Reserves Thursday
# Sunday    -> Reserves Friday

name: Wodify reservation

on:
  schedule:
    - cron: '59 17 * * 0,3-6'  # This is UTC time, so 2pm ET

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}
      GMAIL_APP_PW: ${{ secrets.GMAIL_APP_PW }}
      PABLO_GMAIL: ${{ secrets.PABLO_GMAIL }}
      ALEX_GMAIL: ${{ secrets.ALEX_GMAIL }}
      DEBUGGING: False

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - uses: nanasess/setup-chromedriver@v1
    - name: Install Chromedriver
    # Reference: https://github.com/marketplace/actions/setup-chromedriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &. # optional
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e ".[tests]"
    - name: Wodify reserve
      run: |
        source wodify-reserve.sh
