# This workflow will install Python dependencies, ChromeDriver and run the reservation

# Days to run: 
# Wednesday -> Reserves Monday
# Thursday  -> Reserves Tuesday
# Friday    -> Reserves Wednesday
# Saturday  -> Reserves Thursday
# Sunday    -> Reserves Friday

name: Wodify reservation

on:
  schedule:
    - cron: '58 13 * * 0,3-6'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    
    - uses: nanasess/setup-chromedriver@v1
    - name: Install Chromedriver
    # Reference: https://github.com/marketplace/actions/setup-chromedriver
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        # sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &. # optional
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
  
    - name: Wodify reserve
      run: |
        source wodify-reserve.sh
